config/routes.rb
Rails.application.routes.draw do
  resources :users
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :last_updated, presence: true
	validates :name, presence: true
	validates :email, presence: true
	validates :phone, presence: true
	validates :Status, presence: true
	validates :email, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   protect_from_forgery
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
     @user = User.new
  end

  # GET /users/1 or /users/1.json
  def show
      @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
        format.js   { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js  { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
         format.js   { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js  { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
      format.js  { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:last_updated, :name, :email, :title, :phone, :Status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-secondary bg-secondary">
  <div class="container-fluid">
  	<%= link_to "Users App", users_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
         <%= link_to 'Users', users_path, class:"nav-link" %> 
        </li>

        <!--  <li class="nav-item">
         <%= link_to 'Add User', new_user_path, class:"nav-link" %> 
        </li> -->
       
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to Users App!</h1>
<p>You can create, edit and create users</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Users App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">

     <% if notice %>
      <%= render 'layouts/alerts' %>
     <% end %>
     
      <br/>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>

<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@user, remote: remote, html: {role: :form, 'data-model' => 'user'}) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="field mb-3">
    <%= form.label :last_updated %>
    <%= form.date_select :last_updated %> 

  </div>


  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="field mb-3">
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="field mb-3"> 
    <%= form.text_field :email, class:"form-control", placeholder:"Email"  %>
  </div>

   <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="field mb-3"> 
    <%= form.text_field :title, class:"form-control", placeholder:"Title"  %>
  </div>

   <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="field mb-3"> 
     <%= form.text_field :phone, class:"form-control", placeholder:"Phone"  %>
  </div>

   <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="field mb-3"> 
        <%= form.text_field :Status, class:"form-control", placeholder:"Status"  %>
  </div>

  <%# Added Bootstrap classes %>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>

<% end %>


    






 

app/views/users/_table_row.html.erb
 <tr>
        <td><%= user.last_updated %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.title %></td>
        <td><%= user.phone %></td>
        <td><%= user.Status %></td>
        
        <td><%= link_to 'Show', user %></td>
        <!-- <td><%= link_to 'Edit', edit_user_path(user) %></td> -->
        <td><% link_to 'Edit', '#edit_user_modal', 'data-bs-toggle' => 'modal'%></td>
      

        <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>


      

app/views/users/edit.html.erb
<h1>Editing User</h1>
<br/>
<% render 'form', user: @user %>

<%= link_to 'Edit User', '#edit_user_modal', 'data-bs-toggle' => 'modal', class:"btn btn-danger"%>
<br/>
<div class="modal fade" id="edit_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       
        <h4 class="modal-title" id="myModalLabel">Edit User</h4>
      </div>
      <div class="modal-body">

        <%# Render the new person form (passing modal => true to enable remote => true) %>

        <%= render 'form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<br/>
<%= link_to 'Show', @user, class:"btn btn-secondary" %> 

<%= link_to 'Back', users_path, class:"btn btn-primary" %>

app/views/users/edit.js.erb
// $('#users_table').append("<%= j render partial: 'form', locals: {user: @user } %>");
$("#edit_user_modal").html("<%= j(render partial: 'form', locals: {user: @user}) %>");
$('#edit_user_modal').modal_success();

app/views/users/index.html.erb
<%= link_to 'Create New User', '#new_user_modal', 'data-bs-toggle' => 'modal', class:"btn btn-success"%>
<br/>
<br/>
<h1>Users List</h1>

<table class="table table-hover table-striped table-bordered" id='users_table'>
  <thead class="table-dark">
    <tr>
      <th>Last updated</th>
      <th>Name</th>
      <th>Email</th>
      <th>Title</th>
      <th>Phone</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

     <%# Render table row partial for each user object %>

      <%= render partial: 'table_row', locals: {user: user} %>
    <% end %>
  </tbody>
</table>

<br>

 


<%# Added Bootstrap data modal attribute %>

<%= link_to 'Create New User', '#new_user_modal', 'data-bs-toggle' => 'modal', class:"btn btn-success"%>

<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>

<div class="modal fade" id="new_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       
        <h4 class="modal-title" id="myModalLabel">Create new user</h4>
      </div>
      <div class="modal-body">

        <%# Render the new person form (passing modal => true to enable remote => true) %>

        <%= render 'form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Add New User</h1>

<%= render 'form', user: @user %>

<br/>

<%= link_to 'Back', users_path, class:"btn btn-dark" %> 

app/views/users/show.html.erb
<p>
  <strong>Last updated:</strong>
  <%= @user.last_updated %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.Status %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-primary" %> 
<%= link_to 'Back', users_path, class:"btn btn-secondary" %>

app/views/users/show.js.erb
$('#users_table').append("<%= j render partial: 'table_row', locals: {user: @user } %>");
$('#new_user_modal').modal_success();